### PR TITLE
Track referrals to badge order form

### PR DESCRIPTION
**Pull request by michaelrkn**
This can be tested by visiting signup?referral=whatever. After creating the user, the referral code should be in the DB.

### CODE REVIEW

**Review by rvillanueva — CHANGES_REQUESTED** [review]
Looks good conceptually, but can you investigate why tests are failing here? I suspect it's poor traceability but a real error

**Comment by rvillanueva** [comment]
Try running the test locally and seeing if it shows you where it's failing

**Comment by rvillanueva** [comment]
Feel free to merge when ready

**Review by rvillanueva — APPROVED** [review]

**Comment by michaelrkn** [comment]
Closed in favor of #48.

**Pull request closed without merging**
